### ISSUE TITLE
RS485 standard

### ISSUE THREAD

**Issue by gkasprow** [PSPowerGit/PSPEVSE#1]
Are you sure RS485 uses TTL levels
![obraz](https://github.com/PSPowerGit/PSPEVSE/assets/4325054/d4460d32-4566-456a-bec2-dd8e754693b4)

**Comment by PSPowerGit** [comment]
Yes. SN65176B.

**Comment by gkasprow** [comment]
No, RS485 is differential voltage that has nothing to do with TTL standard.
 SN65176B supports 5V TTL from controller side, RS485 is on the other side of the chip and supports +/-12V or so.

**Comment by gkasprow** [comment]
![obraz](https://github.com/PSPowerGit/PSPEVSE/assets/4325054/5ed50a8b-851d-44f6-9f56-63bf25149ea9)

**Comment by PSPowerGit** [comment]
Please read the datasheet of SN65176B. If the IC is powered at 5V, it generates a 0-5V bus with a voltage tolerance of +/-12V.

**Comment by gkasprow** [comment]
You are mixing the terms
TTL standard has nothing to do with 5V supply.
TTL declares L state as <0.8V, H state >2.1V for input and <0.4 and >2.4 for outputs.
TTL also works with 3.3V supplies
Bus voltage is not 0-5V, it is dependent on common mode voltage and is differential.
![obraz](https://github.com/PSPowerGit/PSPEVSE/assets/4325054/5c9b4cc7-84c1-4a21-a9c9-83a5f29b4f3d)

**Comment by PSPowerGit** [comment]
![TEK0009](https://github.com/PSPowerGit/PSPEVSE/assets/124503153/ea4df927-4400-45e7-b7eb-7b3ffb764c68)

You're right. "TTL" is a wrong abbreviation - documentation error. The bus operates on common positive voltages A/B relative to GND/PE (0-max 5V) and differential voltages +/- ~2.5V (A-B / B-A).

**Comment by gkasprow** [comment]
I bought one recently and wanted to make sure it works with Modbus reliably :)
